name: Auto release excalidraw

env:
  RELEASE_PACKAGE_PATH: "./packages/excalidraw"

on:
  push:
    branches:
      - release

jobs:
  Auto-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Build
        run: |
          yarn
          yarn --cwd ${{ env.RELEASE_PACKAGE_PATH }} build:esm

      - name: Get next version
        uses: anothrNick/github-tag-action@1.64.0
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.17.17
          DEFAULT_BUMP: "patch"

      - name: Increase version from package.json
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "#{"
          tokenSuffix: "}#"
          files: '["${{ env.RELEASE_PACKAGE_PATH }}/package.json"]'
        env:
          version: ${{ steps.get-next-version.outputs.new_tag }}

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.RELEASE_PACKAGE_PATH }}
